[tools]
terraform = "1.15.3"
pre-commit = "4.6.0"
terraform-docs = "0.24.0"
tflint = "0.62.1"
trivy = "0.70.0"
jq = "1.8.1"
conftest = "0.68.2"
opa = "1.16.2"


[tasks.init-local]
description = "Initilize Local Terraform"
run = "AWS_ENDPOINT_URL=http://localhost:4566 terraform init -backend-config=../config/local/backend.hcl"
dir = "src"

[tasks.init-dev]
description = "Initilize Dev Terraform"
run = "terraform init -backend-config=../config/dev/backend.hcl"
dir = "src"

[tasks.plan-local]
description = "Plan Terraform to Local environment"
run = 'AWS_ENDPOINT_URL=http://localhost:4566 terraform plan -var-file="../config/local/us-east-1.tfvars"'
dir = "src"

[tasks.plan-dev]
description = "Plan Terraform to Dev environment"
run = 'terraform plan -var-file="../config/dev/us-east-1.tfvars"'
dir = "src"

[tasks.apply-local]
description = "Apply (Deploy) Terraform to Local environment"
run = 'AWS_ENDPOINT_URL=http://localhost:4566 terraform apply -var-file="../config/local/us-east-1.tfvars"'
dir = "src"

[tasks.apply-dev]
description = "Apply (Deploy) Terraform to Dev environment"
run = 'terraform apply -var-file="../config/dev/us-east-1.tfvars"'
dir = "src"

[tasks.opa-check-local]
description = "Validate Terraform plan against OPA policies using Floci (local)"
run = '''
echo '[INFO] Initializing Terraform for local environment'
AWS_ENDPOINT_URL=http://localhost:4566 terraform init -backend-config=../config/local/backend.hcl -input=false > /dev/null
echo '[INFO] Generating Terraform plan'
AWS_ENDPOINT_URL=http://localhost:4566 terraform plan -var-file="../config/local/us-east-1.tfvars" -out .planfile -input=false > /dev/null
echo '[INFO] Running OPA policies against plan'
terraform show -json .planfile > /tmp/plan.json
conftest test /tmp/plan.json -p ../opa-policies/patterns/ --all-namespaces -o table
rm -f .planfile /tmp/plan.json
'''
dir = "src"

[tasks.pre-commit-install]
description = "Install pre-commit"
run = 'pre-commit install'

[tasks.pre-commit]
description = "Run pre-commit hook on all files"
run = 'pre-commit run -a'

[tasks.floci-up]
description = "Deploy Floci as local AWS emulator and bootstrap the Terraform State S3 Bucket"
run = '''
echo '[INFO] Initializing Floci using Docker Compose'
docker compose up -d
echo '[INFO] Waiting 5s before creating S3 Bucket for local environment'
sleep 5
AWS_ENDPOINT_URL=http://localhost:4566 AWS_SECRET_ACCESS_KEY=test AWS_ACCESS_KEY_ID=test aws s3api create-bucket \
  --bucket terraform-states-local \
  --region us-east-1 \
  --output text >/dev/null 2>&1|| echo "Terraform States bucket might already exist"
'''

[tasks.floci-down]
description = "Deploy Floci as local AWS emulator and bootstrap the Terraform State S3 Bucket"
run = '''
echo '[INFO] Decommissioning Floci'
docker compose down
'''
