repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3
    hooks:
      - id: terraform_validate
        files: src/
      - id: terraform_fmt
        files: src/
      - id: terraform_checkov
        args:
          - --args=--check HIGH
        files: src/
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--use-standard-markers=true
        files: src/
      - id: terraform_tflint
        files: src/
      - id: terraform_trivy
        args:
          - --args=--severity HIGH,CRITICAL
        files: src/
